### PR TITLE
Slight cleaning

### PR DESCRIPTION
**Pull request by baweaver**
Was browsing around, made some small edits that clean up the check a bit and will make it a bit easier to add more later.

### CODE REVIEW

**Comment by eheydrick** [comment]
Can you take a look at the rubocop issues.

**Comment by baweaver** [comment]
Easy enough, will do once I get back

**Comment by GhostLyrics** [comment]
@baweaver any update on this?

**Comment by majormoses** [comment]
@baweaver any chance you are gonna have a chance to push this over the line?

**Comment by majormoses** [comment]
closing due to inactivity, please reply back if you wish to continue so I can re-open.

**Pull request closed without merging**
